import { missions } from './learning';

export type Lesson = {
  title: string; introduction: string;
  sections: { title: string; text: string }[];
  example: { title: string; steps: string[]; explanation: string };
  takeaway: string;
};
export type LearningModule = {
  id: string; title: string; description: string; challengeIds: string[];
  status: 'available' | 'upcoming'; lesson: Lesson;
  plannedChallenges?: string[];
};
export const modules: LearningModule[] = [
  { id: 'sequences', title: 'Sequences', description: 'Give clear instructions, one step at a time.', status: 'available', challengeIds: ['first-steps', 'sequence-up', 'sequence-corner'],
    lesson: { title: 'Every program starts with a sequence', introduction: 'Think about getting ready in the morning: put on your socks, then your shoes. You follow instructions in an order. Computers follow ordered instructions too. We call that order a sequence.',
      sections: [{ title: 'One block, one instruction', text: 'In Robot Rescue, each movement block tells Byte to move exactly one square. Three Move right blocks move Byte three squares right. Byte does only what your program says, so every step needs an instruction.' }, { title: 'Read from top to bottom', text: 'Snap your first block under “when Run is pressed”. The block below it runs next, and the rest follow in order. Blocks left floating on the canvas are not part of your connected program.' }, { title: 'Predict, run, and notice', text: 'Before you press Run, follow the instructions with your finger or imagine Byte moving. After the run, compare your prediction with where Byte stopped. You can change the blocks and try again.' }],
      example: { title: 'A two-step journey', steps: ['Move right', 'Move right'], explanation: 'Byte moves one square right, then another square right. The total movement is two squares.' }, takeaway: 'A sequence is a set of instructions carried out in order.' } },
  { id: 'directions', title: 'Direction & order', description: 'Plan a route and choose what happens first.', status: 'available', challengeIds: ['take-a-turn', 'direction-gap', 'direction-home'],
    lesson: { title: 'The order changes the journey', introduction: 'Two programs can use the same movement blocks and still visit different squares. When rocks are in the way, the order of your instructions can decide whether Byte reaches the station.',
      sections: [{ title: 'Directions follow the screen', text: 'Move up means toward the top of the board. Move down means toward the bottom. Left and right follow the screen too; these commands do not turn when Byte changes position.' }, { title: 'Look at the whole route', text: 'Start with Byte’s square, then find the station and any rocks. Choose clear squares for the route. Sometimes you need to move away from the station for a moment to get around a rock.' }, { title: 'Try a different order', text: 'If moving right leads into a rock, moving up first might open a path. Drag blocks apart and snap them into a new order. Run the new sequence and compare it with the old one.' }],
      example: { title: 'Same moves, different squares', steps: ['Move up', 'Move right'], explanation: 'Byte visits the square above its start before moving right. Reversing these blocks visits the square to the right first.' }, takeaway: 'Think about every square on the route, not only the destination.' } },
  { id: 'loops', title: 'Loops', description: 'Find a pattern and make it repeat.', status: 'available', challengeIds: ['on-repeat', 'loop-corner', 'loop-stairs'],
    lesson: { title: 'Say it once, repeat it with a loop', introduction: 'When you clap four times, you repeat the same action. A loop lets a computer repeat instructions without writing the same blocks over and over.',
      sections: [{ title: 'The count tells us how many times', text: 'A Repeat block has a number. Set it to 4 and the instructions inside run four times. The number is the total number of repetitions, not extra repeats after a first run.' }, { title: 'The body is what repeats', text: 'Drag movement blocks into the space marked “do”. This inside section is the loop body. An empty body gives Byte nothing to do. You can put one movement or a connected sequence inside.' }, { title: 'Combine loops with other blocks', text: 'You can put a normal movement before or after a loop, or connect two loops in a row. The whole program still runs from top to bottom. Look for the part of the route that repeats.' }],
      example: { title: 'Repeat a small pattern', steps: ['Repeat 2 times', '    Move right', '    Move up'], explanation: 'The order is right, up, right, up. Both instructions repeat together.' }, takeaway: 'A loop repeats its whole body the number of times you choose.' } },
  { id: 'debugging', title: 'Debugging', description: 'Use what happened to work out what to change.', status: 'available', challengeIds: ['fix-the-route', 'debug-short', 'debug-order'],
    lesson: { title: 'A bug is a clue', introduction: 'A program does not always do what you intended on the first try. A bug is a problem in the instructions. Debugging means finding that problem, making a change, and checking the result.',
      sections: [{ title: 'Start by watching', text: 'Run the supplied program. Notice the first step where Byte’s route differs from the route you wanted. The highlighted block shows which instruction is running.' }, { title: 'Make one useful change', text: 'A block might point the wrong way, be missing, or appear in the wrong place. Change the part your observation points to. A small change makes it easier to understand why the result changes.' }, { title: 'Test your repair', text: 'Run the program again. Did it reach the station? If not, compare the new feedback with the old feedback. Asking for a hint and trying again are both part of debugging.' }],
      example: { title: 'A missing step', steps: ['Move right', 'Move right', 'Add one more Move right'], explanation: 'If the station is three squares away and Byte stops after two, another rightward step finishes the route.' }, takeaway: 'Observe, change, test. Getting a first attempt wrong is useful information.' } },
  { id: 'variables', title: 'Variables', description: 'Give a value a name, then use and change it.', status: 'upcoming', challengeIds: [], plannedChallenges: ['Name a value', 'Use a stored number', 'Update your value'],
    lesson: { title: 'A name for a value', introduction: 'A variable lets a program store a value under a name. The value can be used later and can change while the program runs.', sections: [{ title: 'A value you can reuse', text: 'For example, a variable named steps could store the number 3. A program could read that value when deciding how many movements to make.' }], example: { title: 'Remember a number', steps: ['Set steps to 3', 'Use steps as a repeat count'], explanation: 'Changing the stored value changes the number the program uses.' }, takeaway: 'Variables challenges and blocks are planned; this module is not playable yet.' } },
  { id: 'conditionals', title: 'Conditionals', description: 'Check something, then choose what to do.', status: 'upcoming', challengeIds: [], plannedChallenges: ['Ask a yes-or-no question', 'Choose between two paths', 'Combine a check with a loop'],
    lesson: { title: 'Make a choice with a condition', introduction: 'A condition is something a program checks. The result tells it which instructions to run. For example: if the path is clear, move; otherwise, choose another direction.', sections: [{ title: 'A check that guides a choice', text: 'A condition has a true or false result. An if block runs its inside instructions only when the condition is true. An else branch describes what to do when it is false.' }], example: { title: 'Check the path', steps: ['If the path is clear', '    Move forward', 'Otherwise, choose another route'], explanation: 'This is a concept example; conditional blocks are not available in the current Robot Rescue editor.' }, takeaway: 'Conditionals challenges and blocks are planned; this module is not playable yet.' } },
  { id: 'project', title: 'Build project', description: 'Bring your ideas together in a route of your own.', status: 'available', challengeIds: ['rescue-project'],
    lesson: { title: 'Make a plan, then make it yours', introduction: 'Now you can use sequences, directions, loops, and debugging together. Your project is to choose a station and build a working route to it.', sections: [{ title: 'Choose your destination', text: 'Select a free square on the board to move the charging station. The starting square and the rock cannot be destinations.' }, { title: 'Build and improve', text: 'Make one working route, then see whether you can find a different one. You might replace repeated movements with a loop or take a different path around the rock.' }], example: { title: 'Your project plan', steps: ['Choose the destination', 'Build a route', 'Run and revise', 'Try another solution'], explanation: 'There is more than one way to solve this project. Explain one choice you made in your program.' }, takeaway: 'A program is something you can create, test, and improve.' } },
];

export function moduleFor(missionId: string): LearningModule { return modules.find(m => m.challengeIds.includes(missionId))!; }
export const challengeOrder = modules.flatMap(m => m.challengeIds);
export function nextChallenge(missionId: string) { return challengeOrder[challengeOrder.indexOf(missionId) + 1]; }
export function missionIndex(id: string) { return missions.findIndex(m => m.id === id); }
