import { useEffect, useState, type ReactNode } from 'react';
import { ArrowRight, BookOpen, Blocks, Check, Gamepad2, Keyboard, Menu, MousePointer2, Play, ShieldCheck, Users, X } from 'lucide-react';
export const adventures = [
  { title: 'Little Explorers', description: 'Arrow blocks and little steps with Byte. Ages 6–8.', image: 'adventure-sky.png', style: 'byte', level: 'Ages 6–8', href: '/#/learn/arrows', activities: '40 challenges + project' },
  { title: 'Code Adventurers', description: 'Text blocks, loops and coding discoveries. Ages 8–10.', image: 'jumping-game.png', style: '', level: 'Ages 8–10', href: '/#/learn/words', activities: '40 challenges + project' },
  { title: 'Independent Builders', description: 'Plan, test and explain your own routes. Ages 10–14.', image: 'adventure-sky.png', style: 'world', level: 'Ages 10–14', href: '/#/learn/builder', activities: '40 challenges + project' },
  { title: 'Computer Explorers', description: 'Practise clicking, dragging and using a keyboard. Ages 6+.', image: 'space-story.png', style: '', level: 'Ages 6+', href: '/#/learn/computer', activities: '20 activities' },
];

export type MarketingPage = 'home' | 'courses' | 'how-it-works' | 'parents';
const destinations = [{ page: 'how-it-works', label: 'How it works' }, { page: 'courses', label: 'Explore' }, { page: 'courses', label: 'Courses' }, { page: 'parents', label: 'For Parents' }];
function Brand() { return <a className="landing-brand" href="/" aria-label="KodeArcade home"><img src="/brand/mark-color.svg" width="36" height="36" alt="" /><span>KodeArcade</span></a>; }
export function MarketingNav({ page, search }: { page: MarketingPage; search?: ReactNode }) {
  const [open, setOpen] = useState(false);
  return <header className="landing-nav"><Brand /><nav id="marketing-navigation" className={open ? 'menu-open' : ''} aria-label="Main navigation">{destinations.map(item => <a key={item.label} href={`/#/${item.page}`} aria-current={item.page === page && item.label !== 'Explore' ? 'page' : undefined} onClick={() => setOpen(false)}>{item.label}</a>)}</nav><div className="nav-actions">{search}<a className="landing-button small" href="/#/learn">Start Learning<ArrowRight size={18} /></a><button className="menu-toggle" aria-label={open ? 'Close navigation' : 'Open navigation'} aria-expanded={open} aria-controls="marketing-navigation" onClick={() => setOpen(!open)}>{open ? <X /> : <Menu />}</button></div></header>;
}
export function MarketingFooter() { return <footer className="landing-footer"><Brand /><nav aria-label="Footer navigation"><a href="/#/how-it-works">How it works</a><a href="/#/courses">Courses</a><a href="/#/parents">For Parents</a></nav><span>A learning preview for curious minds.</span></footer>; }
export default function MarketingPages({ page }: { page: Exclude<MarketingPage, 'home'> }) {
  const [query, setQuery] = useState('');
  const title = page === 'courses' ? 'Courses' : page === 'parents' ? 'For Parents' : 'How it works';
  useEffect(() => { document.title = `${title} | KodeArcade`; return () => { document.title = 'KodeArcade — Play. Build. Learn.'; }; }, [title]);
  const filtered = adventures.filter(course => `${course.title} ${course.description}`.toLowerCase().includes(query.trim().toLowerCase()));
  return <div className={`landing marketing-page marketing-${page}`}><a className="skip-link" href="#main">Skip to content</a><MarketingNav page={page} /><main id="main"><section className="marketing-page-heading"><a className="text-link" href="/">Home<ArrowRight size={16} /></a><h1>{page === 'courses' ? <>Small steps.<br /><span>New worlds.</span></> : page === 'how-it-works' ? <>A little idea.<br /><span>A big adventure.</span></> : <>Their adventure.<br /><span>Your helping hand.</span></>}</h1><p>{page === 'courses' ? 'Arrow blocks, word blocks, or a first go with a mouse. Start where your learner feels ready.' : page === 'how-it-works' ? 'Meet an idea, make a plan, and watch Byte bring it to life. There’s time to try again.' : 'A practical guide to getting started, supporting little learners, and understanding this preview.'}</p></section>
    {page === 'courses' && <><section className="adventures landing-width full-catalog" aria-labelledby="catalog-title"><h2 id="catalog-title">Find their starting point.</h2><p>Choose by confidence, not just age.</p><div className="course-search"><label htmlFor="catalog-query">Find an adventure</label><input id="catalog-query" type="search" value={query} onChange={e => setQuery(e.target.value)} placeholder="Try arrows, loops or keyboard" /><span role="status">{filtered.length} adventures found</span></div><div className="adventure-grid">{filtered.map(course => <article className="adventure-card" key={course.title}><div className="adventure-image"><img src={`/images/${course.image}`} className={course.style} alt="" loading="lazy" /><span className="course-level"><Gamepad2 size={14} />{course.level}</span></div><div className="adventure-copy"><h3>{course.title}</h3><p>{course.description}</p><p>{course.activities}</p><a className="text-link" href={course.href}>Start this course<ArrowRight size={18} /></a></div></article>)}</div>{filtered.length === 0 && <p className="search-empty">No adventures match. <button onClick={() => setQuery('')}>Show all adventures</button></p>}</section>
      <section className="curriculum-guide landing-width"><h2>One world. Ideas that stick.</h2><p>The three coding paths share Robot Rescue’s four-topic curriculum, with ten challenges per topic and a final route-building project. Progress saves separately for each course.</p><ol className="curriculum-list">{[['Sequences', 'Put instructions in order.'], ['Direction & order', 'Plan routes around obstacles.'], ['Loops', 'Repeat useful patterns.'], ['Debugging', 'Find a mistake and try a new idea.']].map(([name, copy]) => <li key={name}><h3>{name}</h3><p>{copy}</p><span>10 challenges</span></li>)}</ol><p className="marketing-note">Little Explorers uses arrows and shorter lessons; the other paths use text blocks. Independent Builders is not yet a separate advanced programming language. Variables and conditionals are planned, not playable.</p></section>
      <section className="computer-overview landing-width"><div><h2>Before coding,<br />get comfortable.</h2><p>Ten mouse activities and ten keyboard activities build confidence with clicking, dragging, finding keys and typing words.</p><a className="landing-button" href="/#/learn/computer">Try computer basics<ArrowRight size={18} /></a></div><ul><li><MousePointer2 />Click, aim, drag and drop</li><li><Keyboard />Space, arrows, letters and words</li><li><Check />Tap and on-screen key alternatives</li></ul></section></>}
    {page === 'how-it-works' && <><section className="learning-intro"><div className="section-intro"><h2>Think it.<br />Build it. Try it.</h2><p>Each challenge starts with a short explanation. Younger learners get a smaller reading step and a visual arrow example.</p></div><ol className="learning-steps"><li><BookOpen /><div><h3>Meet a new idea</h3><p>Read the lesson, look at the example, and find Byte’s goal.</p></div></li><li><Blocks /><div><h3>Make your plan</h3><p>Drag blocks into your program. Little Explorers also has large tap-to-add arrow buttons.</p></div></li><li><Play /><div><h3>Watch what happens</h3><p>Press Play under Byte’s board. Watch the steps finish before feedback appears.</p></div></li></ol></section><section className="practical-guide landing-width"><h2>Three places to explore.</h2><div className="guide-columns"><article><h3>Byte’s world</h3><p>Find the charging star. Watch Byte follow each instruction, then compare the route with your prediction.</p></article><article><h3>Your blocks</h3><p>Arrows for ages 6–8, words for learners ready to read. A repeat block makes a pattern happen again.</p></article><article><h3>Your program</h3><p>Snap instructions below the start block. The canvas stays put while you work, with scrolling for longer programs.</p></article></div><a className="landing-button" href="/#/learn">Give it a go<ArrowRight size={18} /></a></section></>}
    {page === 'parents' && <><section className="support-section"><div><h2>A little help.<br />A lot of possibility.</h2><p>Let your learner take the lead. Hints offer a nudge, and the feedback explains what happened without a race or leaderboard.</p></div><ul><li><Check />Progress saves in this browser</li><li><Check />Optional sounds and reduced-motion settings</li><li><Check />No sign-up needed for this preview</li></ul></section><section className="parent-guide landing-width"><h2>A few ways to help.</h2><div className="guide-columns"><article><Users /><h3>Start together</h3><p>For ages 6–8, try Little Explorers and read the introduction together. New to a mouse? Begin with Computer Explorers.</p></article><article><BookOpen /><h3>Ask, don’t solve</h3><p>“Where will Byte go next?” is a great place to start. Predict a move, press Play, and talk about what happened.</p></article><article><ShieldCheck /><h3>Know what saves</h3><p>Progress stays on this device in this browser. Clearing browser data removes it. There is no account or device sync yet.</p></article></div></section><section className="landing-faq"><h2>Before you begin</h2><details><summary>Which devices can we use?</summary><p>Mouse and touch are supported. A larger screen gives more room for blocks. On-screen keys support computer-basics practice on tablets.</p></details><details><summary>Is this a finished learning platform?</summary><p>This is a working preview. Further curriculum review and learner testing are ahead. We are using feedback from children to improve it.</p></details><details><summary>What about accessibility?</summary><p>Reduced motion, sound controls, tap-to-add arrows and basic keyboard helpers are available. Full keyboard and screen-reader block editing is still being evaluated.</p></details></section></>}
    <section className="landing-final"><h2>Byte’s ready.<br />Where will you take them?</h2><p>One little step is a great place to start.</p><a className="landing-button" href="/#/learn">Try your first challenge<ArrowRight size={20} /></a></section>
  </main><MarketingFooter /></div>;
}
